import type { ToolHandler } from '@simodelne/pgas-server/plugin.js';
import { resolveDomainValue, type HandlerPayload } from './_resolver.js';
import { createStageRuntime, normalizeStageOutput, resolveStageInput } from '../contracts.js';
import { extractDocxText } from '../extract/docx.js';
import { extractPdfText } from '../extract/pdf.js';
import { runStage as runIngest } from '../stages/ingest.js';
import { runStage as runAnonymize } from '../stages/anonymize.js';
import { runStage as runExportAnonymized } from '../stages/export_anonymized.js';
import { runStage as runRehydrate } from '../stages/rehydrate.js';
import { runStage as runExportRestored } from '../stages/export_restored.js';
import { runStage as runFinalize } from '../stages/finalize.js';


// Generated by pgas-new from the approved stage topology. Deterministic stage
// wrappers return values written through action_map.result_path; LLM reasoning
// stages keep the runtime model's tool-call arguments as their source of truth.

export const handlers: Record<string, ToolHandler> = {
  async begin_work(payload) {
    return {
      kind: 'work_started',
      payload,
    };
  },

  async record_user_note(payload) {
    const note = resolveDomainValue<string>(payload as HandlerPayload, 'note', '');
    return {
      kind: 'note_recorded',
      note,
    };
  },

  async session_new(payload) {
    return {
      kind: 'session_control',
      control: 'session_new',
      payload,
    };
  },

  async session_abort_current(payload) {
    return {
      kind: 'session_control',
      control: 'session_abort_current',
      payload,
    };
  },

  async session_status(payload) {
    return {
      kind: 'session_control',
      control: 'session_status',
      payload,
    };
  },

  async session_history(payload) {
    return {
      kind: 'session_control',
      control: 'session_history',
      payload,
    };
  },

  async session_resume(payload) {
    return {
      kind: 'session_control',
      control: 'session_resume',
      payload,
    };
  },

  async session_help(payload) {
    return {
      kind: 'session_control',
      control: 'session_help',
      payload,
    };
  },

  async advance_ingest_to_detect_pii(payload) {
    const output = await runIngest(
      resolveStageInput(payload as HandlerPayload, 'ingest'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'ingest', 'pure-compute', undefined);
  },

  async advance_ingest_to_rehydrate(payload) {
    const output = await runIngest(
      resolveStageInput(payload as HandlerPayload, 'ingest'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'ingest', 'pure-compute', undefined);
  },

  async complete_detect_pii(payload) {
    const resultJson = resolveDomainValue<string>(payload as HandlerPayload, 'result_json', '{}');
    const itemsJson = resolveDomainValue<string>(payload as HandlerPayload, 'items_json', '[]');
    return {
      kind: 'llm_reasoning_stage_output',
      action: 'complete_detect_pii',
      stage: 'detect_pii',
      target: 'anonymize',
      result_json: resultJson,
      items_json: itemsJson,
      payload,
    };
  },

  async complete_anonymize(payload) {
    const output = await runAnonymize(
      resolveStageInput(payload as HandlerPayload, 'anonymize'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'anonymize', 'pure-compute', undefined);
  },

  async complete_export_anonymized(payload) {
    const output = await runExportAnonymized(
      resolveStageInput(payload as HandlerPayload, 'export_anonymized'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'export_anonymized', 'pure-compute', undefined);
  },

  async complete_rehydrate(payload) {
    const output = await runRehydrate(
      resolveStageInput(payload as HandlerPayload, 'rehydrate'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'rehydrate', 'pure-compute', undefined);
  },

  async complete_export_restored(payload) {
    const output = await runExportRestored(
      resolveStageInput(payload as HandlerPayload, 'export_restored'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'export_restored', 'pure-compute', undefined);
  },

  async complete_finalize(payload) {
    const output = await runFinalize(
      resolveStageInput(payload as HandlerPayload, 'finalize'),
      createStageRuntime(payload as HandlerPayload),
    );
    return normalizeStageOutput(output, 'finalize', 'pure-compute', undefined);
  },

  async request_documents(payload) {
    return {
      kind: 'document_upload_requested',
      payload,
    };
  },

  async ingest_documents(payload) {
    return ingestUploadedDocuments(payload as HandlerPayload);
  },
};

async function ingestUploadedDocuments(payload: HandlerPayload): Promise<Record<string, unknown>> {
  if (documentSkipRequestedPayload(payload)) {
    return skippedDocumentSource();
  }
  const request = payload.request as { documents?: unknown } | undefined;
  const rawDocuments = Array.isArray(request?.documents) ? request.documents : [];
  const documentRecords = rawDocuments.filter(isDocumentRecord);
  const allowedMimeTypes = new Set<string>(["text/plain","text/markdown","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/pdf"]);
  const summaries = documentRecords.map(documentSummary);
  const eligible: Array<{ document: Record<string, unknown>; text: string; extraction_kind: string }> = [];
  for (const document of documentRecords) {
    if (!documentMimeAllowed(document, allowedMimeTypes)) {
      continue;
    }
    if (typeof document.content_text === 'string') {
      eligible.push({ document, text: document.content_text, extraction_kind: 'content_text' });
      continue;
    }
    if (documentIsDocx(document) && typeof document.content_base64 === 'string') {
      const bytes = Buffer.from(document.content_base64, 'base64');
      const extracted = extractDocxText(bytes);
      if (!extracted.ok) {
        return {
          status: 'blocked_extraction_failed',
          full_text: '',
          char_count: 0,
          file_count: 0,
          files_json: JSON.stringify(summaries),
          extraction_kind: docxExtractionKind(bytes),
          reason: extracted.reason,
        };
      }
      eligible.push({ document, text: extracted.text, extraction_kind: docxExtractionKind(bytes) });
      continue;
    }
    if (documentIsPdf(document) && typeof document.content_base64 === 'string') {
      const bytes = Buffer.from(document.content_base64, 'base64');
      const extracted = await extractPdfText(bytes);
      if (!extracted.ok) {
        return {
          status: 'blocked_extraction_failed',
          full_text: '',
          char_count: 0,
          file_count: 0,
          files_json: JSON.stringify(summaries),
          extraction_kind: 'pdf',
          reason: extracted.reason,
        };
      }
      eligible.push({ document, text: extracted.text, extraction_kind: 'pdf_pdfjs' });
      continue;
    }
  }

  if (eligible.length === 0) {
    const sawUnsupported = documentRecords.some((document) =>
      typeof document.content_base64 === 'string' || !documentMimeAllowed(document, allowedMimeTypes));
    return {
      status: sawUnsupported ? 'blocked_unsupported_type' : 'blocked_no_content',
      full_text: '',
      char_count: 0,
      file_count: 0,
      files_json: JSON.stringify(summaries),
      extraction_kind: 'none',
      reason: sawUnsupported ? 'uploaded documents were not supported content_text or DOCX content_base64 documents' : 'no engine-injected document content_text was available',
    };
  }

  const fullText = eligible.length === 1
    ? eligible[0]?.text ?? ''
    : eligible.map((entry, index) => `--- file: ${documentName(entry.document, index)} ---\n\n${entry.text}`).join('\n\n');
  const charCount = fullText.length;
  const extractionKind = combinedExtractionKind(eligible.map((entry) => entry.extraction_kind));
  if (charCount < 1) {
    return {
      status: 'blocked_low_fidelity',
      full_text: fullText,
      char_count: charCount,
      file_count: eligible.length,
      files_json: JSON.stringify(eligible.map((entry) => documentSummary(entry.document))),
      extraction_kind: extractionKind,
      reason: `extracted text length ${String(charCount)} below minimum 1`,
    };
  }
  return {
    status: 'extracted',
    full_text: fullText,
    char_count: charCount,
    file_count: eligible.length,
    files_json: JSON.stringify(eligible.map((entry) => documentSummary(entry.document))),
    extraction_kind: extractionKind,
  };
}

function skippedDocumentSource(): Record<string, unknown> {
  return {
    status: 'skipped_no_documents',
    full_text: '',
    char_count: 0,
    file_count: 0,
    files_json: '[]',
    extraction_kind: 'skipped_no_documents',
  };
}

function documentSkipRequestedPayload(payload: HandlerPayload): boolean {
  const domain = payload.domain;
  if (!domain) {
    return false;
  }
  const status = domain['inputs.document_intake.status'];
  if (status === 'no_documents_available') {
    return true;
  }
  const root = domain['inputs.document_intake'];
  return isDocumentRecord(root) && root.status === 'no_documents_available';
}

function documentMimeAllowed(document: Record<string, unknown>, allowedMimeTypes: ReadonlySet<string>): boolean {
  const raw = typeof document.mime_type === 'string'
    ? document.mime_type
    : typeof document.mimeType === 'string'
      ? document.mimeType
      : '';
  return allowedMimeTypes.has(raw.toLowerCase());
}

function documentIsDocx(document: Record<string, unknown>): boolean {
  const raw = typeof document.mime_type === 'string'
    ? document.mime_type
    : typeof document.mimeType === 'string'
      ? document.mimeType
      : '';
  return raw.toLowerCase() === 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
}

function documentIsPdf(document: Record<string, unknown>): boolean {
  const raw = typeof document.mime_type === 'string'
    ? document.mime_type
    : typeof document.mimeType === 'string'
      ? document.mimeType
      : '';
  if (raw.toLowerCase() === 'application/pdf') {
    return true;
  }
  const name = typeof document.name === 'string' ? document.name : typeof document.filename === 'string' ? document.filename : '';
  return name.toLowerCase().endsWith('.pdf');
}

function combinedExtractionKind(kinds: string[]): string {
  if (kinds.length === 1) {
    return kinds[0] ?? 'unknown';
  }
  if (kinds.includes('docx_deflate')) {
    return 'mixed_docx_deflate';
  }
  if (kinds.includes('docx_store')) {
    return 'mixed_docx_store';
  }
  if (kinds.every((kind) => kind === 'content_text')) {
    return 'content_text';
  }
  return kinds.length > 0 ? 'mixed' : 'unknown';
}

function docxExtractionKind(bytes: Uint8Array): string {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  let offset = 0;
  let sawEntry = false;
  let sawDeflate = false;
  while (offset + 4 <= bytes.length && view.getUint32(offset, true) === 0x04034b50) {
    sawEntry = true;
    const method = view.getUint16(offset + 8, true);
    const compressedSize = view.getUint32(offset + 18, true);
    const nameLength = view.getUint16(offset + 26, true);
    const extraLength = view.getUint16(offset + 28, true);
    if (method === 8) {
      sawDeflate = true;
    } else if (method !== 0) {
      return 'docx_unknown';
    }
    const dataEnd = offset + 30 + nameLength + extraLength + compressedSize;
    if (dataEnd > bytes.length) {
      return 'docx_unknown';
    }
    offset = dataEnd;
  }
  if (!sawEntry) {
    return 'docx_unknown';
  }
  return sawDeflate ? 'docx_deflate' : 'docx_store';
}

function documentName(document: Record<string, unknown>, index: number): string {
  return typeof document.name === 'string' && document.name.length > 0
    ? document.name
    : `document-${String(index + 1)}`;
}

function documentSummary(document: Record<string, unknown>): Record<string, unknown> {
  return {
    name: typeof document.name === 'string' ? document.name : undefined,
    mime_type: typeof document.mime_type === 'string'
      ? document.mime_type
      : typeof document.mimeType === 'string'
        ? document.mimeType
        : undefined,
    size: typeof document.size === 'number' ? document.size : undefined,
    has_content_text: typeof document.content_text === 'string',
    has_content_base64: typeof document.content_base64 === 'string',
  };
}

function isDocumentRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}
